package com.bo.bookstore.po;

import java.util.HashSet;
import java.util.Set;

/**
 * BookInfo generated by hbm2java
 */
public class BookInfo implements java.io.Serializable
{

  private Integer id;
  private String doubanReferId;
  private String author;
  private Float rateAverage;
  private String description;
  private String comments;
  private Set<Book> books = new HashSet<Book>(0);

  public BookInfo()
  {
  }

  public BookInfo(String doubanReferId, String author, Float rateAverage,
      String description, String comments, Set<Book> books)
  {
    this.doubanReferId = doubanReferId;
    this.author = author;
    this.rateAverage = rateAverage;
    this.description = description;
    this.comments = comments;
    this.books = books;
  }

  public Integer getId()
  {
    return this.id;
  }

  public void setId(Integer id)
  {
    this.id = id;
  }

  public String getDoubanReferId()
  {
    return this.doubanReferId;
  }

  public void setDoubanReferId(String doubanReferId)
  {
    this.doubanReferId = doubanReferId;
  }

  public String getAuthor()
  {
    return this.author;
  }

  public void setAuthor(String author)
  {
    this.author = author;
  }

  public Float getRateAverage()
  {
    return this.rateAverage;
  }

  public void setRateAverage(Float rateAverage)
  {
    this.rateAverage = rateAverage;
  }

  public String getDescription()
  {
    return this.description;
  }

  public void setDescription(String description)
  {
    this.description = description;
  }

  public String getComments()
  {
    return this.comments;
  }

  public void setComments(String comments)
  {
    this.comments = comments;
  }

  public Set<Book> getBooks()
  {
    return this.books;
  }

  public void setBooks(Set<Book> books)
  {
    this.books = books;
  }

}
